

# This file was *autogenerated* from the file compiguais_tfhe.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_448 = Integer(448); _sage_const_64 = Integer(64); _sage_const_8 = Integer(8)
load("dghv_tfhe.sage")

def compIguais_tfhe(dghv, n=_sage_const_3 ):
    m0 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)
    m1 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)

    print(f"m0 = {m0}")
    print(f"m1 = {m1}")

    bits0 = m0.digits(base=_sage_const_2 , padto=n)
    bits1 = m1.digits(base=_sage_const_2 , padto=n)

    c0 = [dghv.enc_vector(bi) for bi in bits0]
    c1 = [dghv.enc_vector(bi) for bi in bits1]
        # Codifica os bits na forma vetorial

    c = dghv.enc_scalar(_sage_const_1 )
        # Codifica c de forma escalar
    const1 = dghv.enc_vector(_sage_const_1 )
        # Codifica constante 1 para realizar a porta not (c XOR 1)
    for i in range(n):
        cmp_i = dghv.add_vector(c0[i], c1[i])   # c0[i] XOR c1[i]
        cmp_i = dghv.add_vector(cmp_i, const1)  # not cmp_i
        c = dghv.mult(c, cmp_i)             # c AND cmp_i

    res = dghv.dec_scalar(c)
    print(f"Esperado: {_sage_const_1  if m0==m1 else _sage_const_0 } | Res: {res}")
    
dghv = DGHV(_sage_const_448 , _sage_const_64 , _sage_const_8 )
compIguais_tfhe(dghv)

