

# This file was *autogenerated* from the file fulladder-tfhe.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_448 = Integer(448); _sage_const_64 = Integer(64); _sage_const_8 = Integer(8)
load("dghv_tfhe.sage")

def sumLimitedBits(a, b, n):
    mask =  (_sage_const_1  << n) - _sage_const_1 
    res = (a + b) & mask
    return res

def fulladder(dghv, n=_sage_const_3 ):
    m0 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)
    m1 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)

    bitsm0 = m0.digits(base=_sage_const_2 , padto=n)
    bitsm1 = m1.digits(base=_sage_const_2 , padto=n)

    c0_s = [dghv.enc_scalar(bi) for bi in bitsm0]
    c0_v = [dghv.enc_vector(bi) for bi in bitsm0]
    c1_s = [dghv.enc_scalar(bi) for bi in bitsm1]
    c1_v = [dghv.enc_vector(bi) for bi in bitsm1]

    c = []
    cin = dghv.enc_scalar(_sage_const_0 )
    for i in range(n):
        xor_ab = dghv.add_scalar(c0_s[i], c1_s[i])      # scalar
        soma = dghv.add_scalar(xor_ab, cin)             # scalar

        and_ab = dghv.mult(c0_s[i], c1_v[i])            # scalar
        and_acin = dghv.mult(cin, c0_v[i])              # scalar
        and_bcin = dghv.mult(cin, c1_v[i])              # scalar

        cout = dghv.add_scalar(and_ab, dghv.add_scalar(and_acin, and_bcin)) # scalar

        c.append(soma)
        cin = cout 
    
    mbits = [dghv.dec_scalar(ci) for ci in c]

    m = sum((mbits[i] * _sage_const_2 **i) for i in range(n))

    esperado = sumLimitedBits(m0, m1, n)
    if m != esperado:
        print(f"[ERRO] Esperado: {esperado} | Resultado: {m}")
        exit()
    print(f"{m0} + {m1} = {m}")


dghv = DGHV(_sage_const_448 , _sage_const_64 , _sage_const_8 )
fulladder(dghv)

