

# This file was *autogenerated* from the file comp_iguais_bgv-like.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_448 = Integer(448); _sage_const_64 = Integer(64); _sage_const_8 = Integer(8)
load("dghv_bgv-like-2.sage")

def compIguais(dghv, n):
    m0 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)
    m1 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)

    bits0 = m0.digits(base=_sage_const_2 , padto=n)
    bits1 = m1.digits(base=_sage_const_2 , padto=n)

    c0 = [dghv.enc(bi) for bi in bits0]
    c1 = [dghv.enc(bi) for bi in bits1]
        # Codifica os bits na forma vetorial

    c = dghv.enc(_sage_const_1 )
        # Codifica c 
    for i in range(n):
        cmp_i = dghv.add(c0[i], c1[i])       # c0[i] XOR c1[i]
        cmp_i = dghv.not_gate(cmp_i)
        c = dghv.mult(c, cmp_i)              # c = c AND cmp_i

    res = dghv.dec(c)
    if (m0 == m1) != res:
        print(f"m0 = {m0} e m1 = {m1}")
        print(f"[ERRO] Esperado: {m0 == m1} | Resultado: {res}")
        exit(_sage_const_1 )
    print(f"{m0} é {"igual a" if res else "diferente de"} {m1}.")
    
n = _sage_const_3  #Número de bits
dghv = DGHV(_sage_const_448 , _sage_const_64 , _sage_const_8 , n+_sage_const_1 )
compIguais(dghv, n)

# fresco: sk = p e log(ruído) ~= rho
# depois de multiplicar: sk = p' e log(ruído) ~= rho
# os criptogramas podem estar criptografados com ps diferentes
# p0 > p1 > ... > pL
# modulo switching pro nivel certo
# rho = lambda, eta = maior que lambda, gamma = lambda * (eta - rho)^2 / log(lambda) (pensando em segurança)
# lamda -> 2^lambda operações -> lambda é o parâmetro de segurança
# escolha de eta -> baseado no tamanho do primo que depende do circuito
# pra brincar -> lambda pequeno

