

# This file was *autogenerated* from the file dghv_bgv-like.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
load("utils.sage")
load("distributions_acd.sage")

def sample_new_p(eta, rho, p):
    P = random_prime(_sage_const_2 **eta, lbound=_sage_const_2 **(eta - _sage_const_1 )) 
    while P - abs(p/(_sage_const_2 **rho)) > _sage_const_2 **rho :
        P = random_prime(_sage_const_2 **eta, lbound=_sage_const_2 **(eta - _sage_const_1 )) 
    return P

class DGHV:
    def __init__(self, gamma, eta, rho, t = _sage_const_2 , p = _sage_const_1 , b = _sage_const_2 ):
        # __init__ é o contrutor de um objeto da classe
        # self: referência ao próprio objeto (obrigatório em métodos de classe)
        # gamma, eta, rho: parâmetros de segurança do esquema
        # t: espaço da mensagem (padrão = 2, para bits 0, 1)
        # p: chave secreta (primo)
        assert(gamma > eta)
        assert(eta > rho)
            # Garantem que essas condições são verdadeiras
            # Caso sejam falsas, o programa para gerando AssertionError
        if _sage_const_1  == p:
            p = random_prime(_sage_const_2 **eta, lbound=_sage_const_2 **(eta - _sage_const_1 ))
                # lbound: lower bound, valor mínimo de retorno
        else:
            # se p é dado, precisa ter eta bits
            assert(eta - _sage_const_1  <= p.nbits() <= eta)
        
        self.gamma = gamma
        self.eta = eta
        self.rho = rho
        self.t = t
        self.p = p
            # Armazena os atributos do objeto
            # self.xxxx cria variáveis que pertencem ao objeto
        qq = sample_q(gamma, eta)
        while (qq == _sage_const_0 ):
            qq = sample_q(gamma, eta)
        self.x0 = p * qq # + self.sample_r()
            # Gera chave pública x0; limitará o tamanho do texto cifrado
        self.Zp = ZZ.quotient(p)
        self.Zx0 = ZZ.quotient(self.x0)
            # Cria anéis queociente para aritmética modular
            # ZZ.quotient(p) -> Anel dos inteiros módulo p
            # ZZ.quotient(self.x0) -> Anel dos inteiros módulo x0
        self.b = b 
        self.l = floor(log(_sage_const_2 **self.gamma, b)) + _sage_const_1 
        
        # Método enc - crifação (encryption):
    def enc(self, m): # self - acesso aos atributos do objeto; m - mensagem a ser cifrada
        q = sample_q(self.gamma, self.eta)
        r = sample_r(self.rho)
        x = self.p * q + r
        c = x + m
        return c

    def dec(self, c):
        noisy_msg = sym_mod(c, self.p)
        m = noisy_msg % self.t
        return m
    
    # Operações homomórficas:    
    def add(self, c0, c1): # soma com criptogramas escalares
        return (c0 + c1) % self.x0

    def mult(self, c0, c1): # multiplicação
        temp_c = c0 * c1
        
        # Creating modulus-switching key
        P = sample_new_p(self.eta, self.rho, self.p) # p' é aleatório? p' vira a nova chave secreta?
        Q = [(P * sample_q(self.gamma, self.eta)) for i in range(self.l)] # p' * q vector
        R = [sample_r(self.rho) for i in range(self.l)]
        G = [round((P/(self.t * self.p)) * (self.b)**i) for i in range(self.l)] # p'/(t*p) * gadget vector
        k = [(Q[i] + R[i] + G[i]) for i in range(self.l)] # modulus-switching key

        # Decomposing c
        y = temp_c.digits(base=self.b, padto=self.l)

        # Computing the product
        c = self.t * sum((y[i] * k[i]) for i in range(self.l)) + (temp_c % self.t)
        
        # Saving the new secret key (se isso tiver certo mesmo)
        self.p = P

        return c

