

# This file was *autogenerated* from the file fulladder-bgv-like.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_512 = Integer(512); _sage_const_256 = Integer(256); _sage_const_16 = Integer(16); _sage_const_3 = Integer(3)
load("dghv_bgv-like-2.sage")

def sumLimitedBits(a, b, n):
    mask =  (_sage_const_1  << n) - _sage_const_1 
    res = (a + b) & mask
    return res

def fulladder(dghv, n): # n = quantidade de bits dos números
    m0 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)
    m1 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)

    bits0 = m0.digits(base=_sage_const_2 , padto=n)
    bits1 = m1.digits(base=_sage_const_2 , padto=n)

    c0 = [dghv.enc(bi) for bi in bits0]
    c1 = [dghv.enc(bi) for bi in bits1]

    c = []              # bits res
    cin = dghv.enc(_sage_const_0 )   # primeiro cin
    for i in range(n):
        # Soma do bit atual
        print(f"[Par {i}]: {dghv.dec(c0[i])} e {dghv.dec(c1[i])}")
        xor_ab = dghv.add(c0[i], c1[i])
        soma = dghv.add(xor_ab, cin)    # Resultado da soma dos bits
        print(f"\tSoma: {dghv.dec(soma)}")

        # Cálculo do carry out (cout)
        and_ab = dghv.mult(c0[i], c1[i])
        and_xor_ab_cin = dghv.mult(xor_ab, cin)
        cout = dghv.or_gate(and_ab, and_xor_ab_cin)
        print(f"\tCout: {dghv.dec(cout)}")
        c.append(soma)                  # bit da soma criptografado
        cin = cout

    mbits = [dghv.dec(ci) for ci in c]

    m = _sage_const_0 
    for i in range(n):
        m += mbits[i] * (_sage_const_2 **i)
    # m deve ser a mensagem descriptografada (soma dos valores m1 e m2 iniciais)

    esperado = sumLimitedBits(m0, m1, n)
    if m != esperado:
        print(f"[ERRO] Esperado: {esperado} | Resultado: {m}")
        exit(_sage_const_1 )
    print(f"{m0} + {m1} = {m}")

dghv = DGHV(_sage_const_512 , _sage_const_256 , _sage_const_16 , _sage_const_3 )
fulladder(dghv, _sage_const_1 )

