

# This file was *autogenerated* from the file compIguais.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_25 = Integer(25); _sage_const_20 = Integer(20); _sage_const_5 = Integer(5)
load("dghv.sage")

def comparacao_homomorfica (dghv , n=_sage_const_3 ):
    m0 = ZZ. random_element (_sage_const_0 , _sage_const_2 **n)
    m1 = ZZ. random_element (_sage_const_0 , _sage_const_2 **n)
    print(m0)
    print(m1)
    bits0 = m0.digits(base =_sage_const_2 , padto=n) # lista com n bits
    bits1 = m1.digits(base =_sage_const_2 , padto=n) # lista com n bits
    c0 = [dghv.enc(bi) for bi in bits0] # cifra cada bit
    c1 = [dghv.enc(bi) for bi in bits1] # cifra cada bit
    # compara homomorficamente
    c, m = _sage_const_1 , _sage_const_1 
    for i in range(n):
        cmp_i = dghv.add(c0[i], c1[i]) # enc(0) <==> c0[i] == c1[i]
        cmp_i = dghv.not_gate(cmp_i) # enc(1) <==> c0[i] == c1[i]
        c = dghv.mult(c, cmp_i) # c *= cmp_i
    # decifra e verifica
    print(c)
    res = dghv.dec(c)
    print(m0 == m1)
    print(res)
    return ((m0 == m1) == res)

dghv = DGHV(_sage_const_25 , _sage_const_20 , _sage_const_5 )
print(comparacao_homomorfica(dghv))

