

# This file was *autogenerated* from the file fulladder.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_512 = Integer(512); _sage_const_256 = Integer(256); _sage_const_16 = Integer(16)
load("dghv.sage")

def sumLimitedBits(a, b, n):
    mask =  (_sage_const_1  << n) - _sage_const_1 
    res = (a + b) & mask
    return res

def fulladder(dghv, n=_sage_const_3 ):    # n => quantidade de bits
    m1 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)
    m2 = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)   # Escolhe dois números inteiros aleatórios
    print("m1: ", m1)
    print("m2: ", m2)
    bits1 = m1.digits(base=_sage_const_2 , padto=n)
    bits2 = m2.digits(base=_sage_const_2 , padto=n)    # Listas com os bits de cada número
    print("bits 1: ", bits1)
    print("bits 2: ", bits2)

    c1 = [dghv.enc(bi) for bi in bits1]
    c2 = [dghv.enc(bi) for bi in bits2]     # Listas com os bits criptografados de cada número

    # full adder
    c = [None] * n
    cin = dghv.enc(_sage_const_0 )
    for i in range(n):
        idx = i

        # Soma do bit atual
        xor_ab = dghv.add(c1[idx], c2[idx])    
        sum = dghv.add(xor_ab, cin)         # Resultado

        # Cálculo do carry out
        and_ab = dghv.mult(c1[idx], c2[idx])
        and_xor_ab_cin = dghv.mult(xor_ab, cin)
        cout = dghv.or_gate(and_ab, and_xor_ab_cin)

        c[idx] = sum                      # mensagem criptografada
        cin = cout
    
    
    mbits = [dghv.dec(ci) for ci in c]
    print("mbits: ", mbits)    # Debuggando

    m = _sage_const_0 
    for i in range(n):
        m += mbits[i] * (_sage_const_2 **i)
    # m deve ser a mensagem descriptografada (soma dos valores m1 e m2 iniciais)

    esperado = sumLimitedBits(m1, m2, n)
    print("Resultado: ", m, " | Esperado: ", esperado)
    return m == esperado

dghv = DGHV(_sage_const_512 , _sage_const_256 , _sage_const_16 )
fulladder(dghv)

