

# This file was *autogenerated* from the file mairoque.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_7500 = Integer(7500); _sage_const_800 = Integer(800); _sage_const_40 = Integer(40)
load("dghv.sage")

def maior(dghv, n=_sage_const_3 ):               # n => quantidade de bits
    A = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)
    B = ZZ.random_element(_sage_const_0 , _sage_const_2 **n)      # Escolhe dois números inteiros aleatórios
    print("A: ", A)
    print("B: ", B)

    bitsA = A.digits(base=_sage_const_2 , padto=n)
    bitsB = B.digits(base=_sage_const_2 , padto=n)  # Listas com os bits de cada número
    print(f"Bits A: {bitsA}\nBits B: {bitsB}")

    ac = [dghv.enc(bi) for bi in bitsA]
    bc = [dghv.enc(bi) for bi in bitsB] # Listas com os bits criptografados de cada número

    maior = dghv.enc(_sage_const_0 )
    igualAntes = dghv.enc(_sage_const_1 )
    for i in range(n):
        idx = n - _sage_const_1  - i
        print("pos = ", idx)
        # Se os números ainda são iguais, verifica bit atual
        a_Maior = dghv.mult(dghv.mult(ac[idx], dghv.not_gate(bc[idx])), igualAntes)
        print(f"\ta_Maior: {dghv.dec(a_Maior)}")

        # Atualiza maior (maior OR a_Maior)
        print(f"\tMaior antes: {dghv.dec(maior)}")
        maior = dghv.or_gate(maior, a_Maior)
        print(f"\tMaior depois: {dghv.dec(maior)}")

        # Verifica se os bits analisados são iguais
        iguais = dghv.add(ac[idx], bc[idx])
        iguais = dghv.not_gate(iguais)

        # Set igualAntes pra próxima iteração
        # Verifica se os números continuam iguais
        igualAntes = dghv.mult(iguais, igualAntes)
    
    # resposta está no maior
    res = dghv.dec(maior)
    print(f"Resposta: {res}")
    print(f"Esperado: {_sage_const_1  if A > B else _sage_const_0 }")


dghv = DGHV(_sage_const_7500 , _sage_const_800 , _sage_const_40 )
maior(dghv)

